security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        user_db_provider:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                provider: user_db_provider
                default_target_path: dashboard
                login_path: login
                check_path: login
    access_control:
        - { path: ^\/(|login|register|register/team/[a-f0-9]*|locale)$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }